# Generated by Django 3.1.7 on 2021-03-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
